
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmbekgrrrndmlberoeta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tYmVrZ3Jycm5kbWxiZXJvZXRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NTk0MDEsImV4cCI6MjA2MTUzNTQwMX0.MWgn0z50bSjhw2a-LAWifREM0xOCa-anY4W8wGwoLkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage,
    debug: true  // Enable debug mode for authentication
  },
});

// Add a debug helper to track auth state
supabase.auth.onAuthStateChange((event, session) => {
  console.log('Auth state changed:', event, session ? 'User authenticated' : 'User signed out', session);
});
